version: "3"

services:
  my_app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./concursei_br/data:/app/concursei_br/data
      - ./concursei_br/app:/app/concursei_br/app